# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(761, 391)
        self.pushButton_create = QtWidgets.QPushButton(Form)
        self.pushButton_create.setGeometry(QtCore.QRect(130, 90, 161, 51))
        self.pushButton_create.setObjectName("pushButton_create")
        self.textEdit = QtWidgets.QTextEdit(Form)

        self.textEdit.setGeometry(QtCore.QRect(190, 240, 381, 71))
        self.textEdit.setObjectName("textEdit")
        self.pushButton_clear = QtWidgets.QPushButton(Form)
        self.pushButton_clear.setGeometry(QtCore.QRect(420, 100, 121, 51))
        self.pushButton_clear.setObjectName("pushButton_clear")

        self.retranslateUi(Form)
        self.pushButton_create.clicked.connect(self.textEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "ORC"))
        self.pushButton_create.setText(_translate("Form", "生成"))
        self.pushButton_clear.setText(_translate("Form", "清除"))
